<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 Regresión lineal simple. | 2673 Regresion lineal</title>
  <meta name="description" content="Chapter 2 Regresión lineal simple. | 2673 Regresion lineal" />
  <meta name="generator" content="bookdown 0.37 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 Regresión lineal simple. | 2673 Regresion lineal" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 Regresión lineal simple. | 2673 Regresion lineal" />
  
  
  

<meta name="author" content="A.J. Signes-Pastor" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="regresión-multiple.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Regresion lineal</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Análisis de regresión</a></li>
<li class="chapter" data-level="2" data-path="regresión-lineal-simple..html"><a href="regresión-lineal-simple..html"><i class="fa fa-check"></i><b>2</b> Regresión lineal simple.</a>
<ul>
<li class="chapter" data-level="2.1" data-path="regresión-lineal-simple..html"><a href="regresión-lineal-simple..html#ejemplo-base-de-datos-women"><i class="fa fa-check"></i><b>2.1</b> Ejemplo base de datos “women”</a></li>
<li class="chapter" data-level="2.2" data-path="regresión-lineal-simple..html"><a href="regresión-lineal-simple..html#diagnosticos-de-la-regresión"><i class="fa fa-check"></i><b>2.2</b> Diagnosticos de la regresión</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="regresión-multiple.html"><a href="regresión-multiple.html"><i class="fa fa-check"></i><b>3</b> Regresión multiple</a>
<ul>
<li class="chapter" data-level="3.1" data-path="regresión-multiple.html"><a href="regresión-multiple.html#ejemplo-base-de-datos-state.x77"><i class="fa fa-check"></i><b>3.1</b> Ejemplo base de datos “state.x77”</a></li>
<li class="chapter" data-level="3.2" data-path="regresión-multiple.html"><a href="regresión-multiple.html#diagnostico-de-la-regresión"><i class="fa fa-check"></i><b>3.2</b> Diagnostico de la regresión</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="caso-práctico.html"><a href="caso-práctico.html"><i class="fa fa-check"></i><b>4</b> Caso práctico</a>
<ul>
<li class="chapter" data-level="4.1" data-path="caso-práctico.html"><a href="caso-práctico.html#nhanes"><i class="fa fa-check"></i><b>4.1</b> NHANES</a></li>
<li class="chapter" data-level="4.2" data-path="caso-práctico.html"><a href="caso-práctico.html#metales-y-crecimiento"><i class="fa fa-check"></i><b>4.2</b> Metales y crecimiento</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="regresión-logistica.html"><a href="regresión-logistica.html"><i class="fa fa-check"></i><b>5</b> Regresión logistica</a>
<ul>
<li class="chapter" data-level="5.1" data-path="regresión-logistica.html"><a href="regresión-logistica.html#ejemplo"><i class="fa fa-check"></i><b>5.1</b> Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="referencias.html"><a href="referencias.html"><i class="fa fa-check"></i><b>6</b> Referencias</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">2673 Regresion lineal</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="regresión-lineal-simple." class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">Chapter 2</span> Regresión lineal simple.<a href="regresión-lineal-simple..html#regresión-lineal-simple." class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="ejemplo-base-de-datos-women" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> Ejemplo base de datos “women”<a href="regresión-lineal-simple..html#ejemplo-base-de-datos-women" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><a href="https://urldefense.com/v3/__https://posit.cloud/content/5315975__;!!D9dNQwwGXtA!TgcUyMlKMXUZJQdiWTdY8W2MD6XZ33GVA8jyFJxv-50ItD2jDZPi1f7oM_3JHqx5qkmwQCrz8hmvPq7f$">Acceso al código R</a></p>
<p>Utilizaremos la base de datos preinstalada <em>women</em>. Esta base de datos proporciona la altura y peso de un grupo de 15 mujeres.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="regresión-lineal-simple..html#cb1-1" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code></pre></div>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="regresión-lineal-simple..html#cb2-1" tabindex="-1"></a><span class="fu">help</span>(women)</span>
<span id="cb2-2"><a href="regresión-lineal-simple..html#cb2-2" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(weight <span class="sc">~</span> height, <span class="at">data=</span>women)</span>
<span id="cb2-3"><a href="regresión-lineal-simple..html#cb2-3" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = weight ~ height, data = women)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -1.7333 -1.1333 -0.3833  0.7417  3.1167 
## 
## Coefficients:
##              Estimate Std. Error t value           Pr(&gt;|t|)    
## (Intercept) -87.51667    5.93694  -14.74 0.0000000017110819 ***
## height        3.45000    0.09114   37.85 0.0000000000000109 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.525 on 13 degrees of freedom
## Multiple R-squared:  0.991,  Adjusted R-squared:  0.9903 
## F-statistic:  1433 on 1 and 13 DF,  p-value: 0.00000000000001091</code></pre>
<ul>
<li><p>En la salida podemos observar la fórmula del modelo. El peso “weight” es la variable dependiente y altura “height” es la variable independiente o explicativa.</p></li>
<li><p>El siguiente elemento son los residuos “Residuals”. Los residuos son básicamente la diferencia entre el valor actual observado y el valor respuesta estimado con el modelo. La sección de residuos muestra el valor mínimo, primer cuartil, mediana, tercer cuartil, y valor máximo. Con el fin de evaluar cómo de bueno es el ajuste del modelo nos fijamos en la simetría de la distribución. En nuestro caso la mediana/media de los residuos es cercana a 0, lo que sugiere que el modelo se ajusta bastante bien a los valores observados.</p></li>
<li><p>La siguiente sección se refiere a los coeficientes del modelo. Teóricamente, en la regresión simple, los coeficientes son dos constantes desconocidas que representan la intersección y la pendiente de los términos del modelo lineal. La intersección y la pendiente son el resultado de generar la línea de ajuste lo más cercana posible a los puntos de nuestra base de datos.</p>
<ul>
<li><p>“Estimate” tiene dos filas. La primera es la intersección. La segunda file es la pendiente. En nuestro ejemplo la asociación entre el peso y la altura. La pendiente en nuestro ejemplo nos dice que por cada pulgada (in) en altura el peso aumenta 3.45 libras (1 lbs = 0.453 kg).</p></li>
<li><p>“Standard Error” mide la cantidad media que los coeficientes estimados varia de la cantidad real media en nuestra variable respuesta. En una situación ideal queremos valores pequeños en relación con sus coeficientes. En nuestro ejemplo, observamos que por cada pulgada en altura el peso aumenta 3.45 libras. El error estándar se puede utilizar para obtener un estimador de la diferencia esperada en el caso que ejecutemos el modelo una y otra vez. En otras palabras, podemos decir que en peso estimado puede variar en 0.091 pulgadas. Los errores estándar también pueden utilizarse para calcular los intervalos de confianza y para evaluar estadísticamente la hipótesis de asociación entre la altura y peso existe.</p></li>
<li><p>“t-value” es la medida de cuantas desviaciones estándar nuestros coeficientes se alejan de 0. Queremos que se alejen de 0, pues esto indicaría que podemos rechazar la hipótesis nula. Esto significa que podríamos confirmar la existencia de una asociación entre la altura y el peso. En nuestro ejemplo, el valor “t-statistic” están alejados de 0 y son grandes en relación con los errores standard, lo cual indica que la relación entre la altura y el peso existe. En general, los “t-value” se utilizan para determinar los “p-value”.</p></li>
<li><p>“Pr(&gt;t)” se refiere a la probabilidad de observar un valor igual o más grande que t. Un “p-value” pequeño indica que es poco probable observar una relación entre la variable predictora (altura) y la variable respuesta (peso) debido al azar. Tradicionalmente, un “p-value” 5% o más pequeño como punto de corte. En nuestro ejemplo, el “p-value” son cercanos a 0. Un valor pequeño de “p-value” para la intersección y pendiente indica que podemos rechazar la hipótesis nula, lo que nos permite concluir que hay una relación entre la altura y el peso.</p></li>
</ul></li>
<li><p>El “Residual Standard Error” es una medida de la calidad de la regresión lineal. En teoría, en un modelo lineal se asume un término de error. Debido al término de error, no podemos predecir perfectamente la variable respuesta (peso) a partir de nuestra variable predictora (altura). En nuestro ejemplo, el peso estimado puede desviarse de la verdadera línea de regresión en aproximadamente 1.525 libras como media. En nuestro ejemplo el “Residual Standard Error” se ha calculado con 13 grados de libertad. De una forma simplista, los valores o grados de libertad son número de datos que se utilizaron en la estimación de los parámetros después de tener en cuenta dichos parámetros (restricción). En nuestro caso, tenemos 15 datos y 2 parámetros (intersección y pendiente).</p></li>
<li><p>“Multiple R-squared, Adjusted R-squared” son medidas que nos proporcionan información de cómo de bueno es el ajuste. “Multiple R-squared” es una medida de la relación lineal entre nuestra variable predictora (altura) y nuestra variable respuesta (peso). Toma un valor entre 0 y 1 (un número cercano a 0 indica que la regresión no explica bien la variabilidad de la variable respuesta y un número cercano a 1 explica la variabilidad observada en la variable respuesta). En nuestro ejemplo, “Multiple R-squared” es 0.991 o 99% de la variabilidad encontrada en la variable respuesta (peso) se puede explicar con la variable predictora (altura). “Multiple R-squared” siempre aumenta con la inclusión de más variable predictoras en el modelo. Debido a esto se utiliza “Adjusted R-squared” que está ajustado por el número de variables consideradas.</p></li>
<li><p>“F-Statistic” es un buen indicador para saber si existe una relación en la variable predictora y la variable respuesta. Si el “F-Statistic” se aleja de 1 es una buena señal. Sin embargo, cuánto más grande debe ser “F-Statistic” depende tanto del número de datos como del número de predictores. Generalmente, cuando el número de datos es grande, un estadístico F que sea solo un poco mayor que 1 ya es suficiente para rechazar la hipótesis nula. Si el número de puntos de datos es pequeño, se requiere un “F-Statistic” grande para poder determinar que puede haber una relación entre las variables de predicción y respuesta. En nuestro ejemplo, el “F-Statistic” es 1433, que es mucho mayor que 1 dado el tamaño de nuestros datos <span class="citation">(Kabacoff, 2011)</span>.</p></li>
</ul>
<p><!--https://feliperego.github.io/blog/2015/10/23/Interpreting-Model-Output-In-R # I have used this to interpret the outcome.--></p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="regresión-lineal-simple..html#cb4-1" tabindex="-1"></a>fit.res <span class="ot">&lt;-</span> fit<span class="sc">$</span>residuals</span>
<span id="cb4-2"><a href="regresión-lineal-simple..html#cb4-2" tabindex="-1"></a><span class="fu">mean</span>(fit.res)</span></code></pre></div>
<pre><code>## [1] 0.00000000000000004808075</code></pre>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="regresión-lineal-simple..html#cb6-1" tabindex="-1"></a><span class="fu">plot</span>(women<span class="sc">$</span>height, fit.res)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="regresión-lineal-simple..html#cb7-1" tabindex="-1"></a>women<span class="sc">$</span>weight</span></code></pre></div>
<pre><code>##  [1] 115 117 120 123 126 129 132 135 139 142 146 150 154 159 164</code></pre>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="regresión-lineal-simple..html#cb9-1" tabindex="-1"></a><span class="fu">residuals</span>(fit)</span></code></pre></div>
<pre><code>##           1           2           3           4           5           6           7           8           9          10          11 
##  2.41666667  0.96666667  0.51666667  0.06666667 -0.38333333 -0.83333333 -1.28333333 -1.73333333 -1.18333333 -1.63333333 -1.08333333 
##          12          13          14          15 
## -0.53333333  0.01666667  1.56666667  3.11666667</code></pre>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="regresión-lineal-simple..html#cb11-1" tabindex="-1"></a><span class="co">#par(mfrow=c(1,1))</span></span>
<span id="cb11-2"><a href="regresión-lineal-simple..html#cb11-2" tabindex="-1"></a><span class="fu">plot</span>(women<span class="sc">$</span>height,women<span class="sc">$</span>weight,</span>
<span id="cb11-3"><a href="regresión-lineal-simple..html#cb11-3" tabindex="-1"></a>               <span class="at">xlab=</span><span class="st">&quot;Height (in inches)&quot;</span>,</span>
<span id="cb11-4"><a href="regresión-lineal-simple..html#cb11-4" tabindex="-1"></a>               <span class="at">ylab=</span><span class="st">&quot;Weight (in pounds)&quot;</span>) </span>
<span id="cb11-5"><a href="regresión-lineal-simple..html#cb11-5" tabindex="-1"></a></span>
<span id="cb11-6"><a href="regresión-lineal-simple..html#cb11-6" tabindex="-1"></a><span class="fu">abline</span>(fit)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="regresión-lineal-simple..html#cb12-1" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb12-2"><a href="regresión-lineal-simple..html#cb12-2" tabindex="-1"></a>women<span class="sc">$</span>predicted <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit) </span>
<span id="cb12-3"><a href="regresión-lineal-simple..html#cb12-3" tabindex="-1"></a><span class="fu">ggplot</span>(women, <span class="fu">aes</span>(<span class="at">x =</span> height, <span class="at">y =</span> weight)) <span class="sc">+</span></span>
<span id="cb12-4"><a href="regresión-lineal-simple..html#cb12-4" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">&quot;lightgrey&quot;</span>) <span class="sc">+</span>  </span>
<span id="cb12-5"><a href="regresión-lineal-simple..html#cb12-5" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">xend =</span> height, <span class="at">yend =</span> predicted), <span class="at">alpha =</span> .<span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb12-6"><a href="regresión-lineal-simple..html#cb12-6" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb12-7"><a href="regresión-lineal-simple..html#cb12-7" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y =</span> predicted), <span class="at">shape =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb12-8"><a href="regresión-lineal-simple..html#cb12-8" tabindex="-1"></a>  <span class="fu">theme_bw</span>() </span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>Con la información generada se puede predecir que la ecuación es:</p>
<p><span class="math inline">\(\hat{weight} = -87.52 + 3.45 x height\)</span></p>
<p><br/></p>
<p>Una altura de 0 es imposible, por lo tanto, es complicado darle una interpretación a la intersección. La intersección en este caso es solamente un constante de ajuste. De la columna Pr(&gt;|t|), podemos ver que el coeficiente de regresión (3.45) es significativamente diferente de cero (p &lt; 0.001) e indica que hay un incremento esperado de 3.45 libra de peso por cado 1 pulgada de aumento en la altura. La multiple “R-squared” (0.991) indica que el modelo explica el 99.1% de la varianza en pesos. El error residual estándar (1.53 libra) se puede interpretar como la media de error en el peso estimado por la altura usando el presente modelo. Podemos observar que los residuales más grande tiene lugar para las alturas más bajas y altas.</p>
<p><br/></p>
</div>
<div id="diagnosticos-de-la-regresión" class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Diagnosticos de la regresión<a href="regresión-lineal-simple..html#diagnosticos-de-la-regresión" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>De momento no sabemos si el modelo generado es adecuado. Hay que tener en cuenta que los parámetros de la regresión dependen del grado con el que se cumplen las asunciones estadísticas de los métodos de mínimos cuadrados.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="regresión-lineal-simple..html#cb14-1" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(weight <span class="sc">~</span> height, <span class="at">data=</span>women)</span>
<span id="cb14-2"><a href="regresión-lineal-simple..html#cb14-2" tabindex="-1"></a><span class="co">#par(mfrow=c(2,2))</span></span>
<span id="cb14-3"><a href="regresión-lineal-simple..html#cb14-3" tabindex="-1"></a><span class="fu">plot</span>(fit)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-10-1.png" width="672" /><img src="bookdownproj_files/figure-html/unnamed-chunk-10-2.png" width="672" /><img src="bookdownproj_files/figure-html/unnamed-chunk-10-3.png" width="672" /><img src="bookdownproj_files/figure-html/unnamed-chunk-10-4.png" width="672" /></p>
<p>Para entender los gráficos generados, hay que tener en cuenta las asunciones para los modelos de mínimos cuadrados:</p>
<ul>
<li><p><strong>Normalidad</strong>: si la variable dependiente se distribuye normalmente para un conjunto fijo de valores predictores, entonces los valores residuales deben distribuirse normalmente con una media de 0. La gráfica de QQ normal es una gráfica de probabilidad de los residuos estandarizados frente a los valores que se esperaría bajo normalidad. Si ha cumplido con la suposición de normalidad, los puntos de este gráfico deben estar en la línea recta de 45 grados. Como no es así, claramente ha violado ligeramente supuesto de normalidad.</p></li>
<li><p><strong>Independencia</strong>: no se puede saber si los valores de las variables dependientes son independientes. Se debe de conocer cómo se recogieron los datos. No hay ninguna razón <em>a priori</em> para creer que el peso de una mujer influye en el peso de otra. Si se incluyeran datos de una misma familia, es posible que fuera necesario ajustar por el supuesto de independencia.</p></li>
<li><p><strong>Linealidad</strong>: si la variable dependiente está relacionada linealmente con las variables independientes, no debe haber una relación sistemática entre los residuos y los valores estimados (“Residuals vs Fitted”). En otras palabras, el modelo debe capturar toda la varianza sistemática presente en los datos, sin dejar nada más que ruido aleatorio. En el gráfico de Residuos vs. Ajustado, verá una clara evidencia de una relación curva, lo que sugiere que es posible que desee agregar un término cuadrático a la regresión.</p></li>
<li><p><strong>Homoscedasticidad</strong>: si ha cumplido con el supuesto de varianza constante, los puntos en el gráfico Escala-Ubicación (Scale-Location) deben ser una banda aleatoria alrededor de una línea horizontal. Parece cumplir con esta suposición.</p></li>
</ul>
<p><br/></p>
<p>Finalmente, el gráfico de <em>Residuals vs. Leverage</em> proporciona información sobre las observaciones individuales que quizás desee atender. El gráfico identifica valores atípicos, puntos de influciencia alta y observaciones influyentes. Específicamente:</p>
<ul>
<li><p>Un valor atípico es una observación que no se predice bien mediante el modelo de regresión ajustado (es decir, tiene un gran residuo positivo o negativo).</p></li>
<li><p>Una observación con un valor de influencia alto tiene una combinación inusual de valores de predicción. Es decir, es un valor atípico en el espacio de predicción. El valor de la variable dependiente no se usa para calcular el la influencia de una observación.</p></li>
<li><p>Una observación influyente es una observación que tiene un impacto desproporcionado en la determinación de los parámetros del modelo. Las observaciones influyentes se identifican mediante una estadística llamada distancia de Cook o D. de Cook.</p></li>
</ul>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="regresión-multiple.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/Tonis81/2673_Regresion_lineal/edit/main/02-simple.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/Tonis81/2673_Regresion_lineal/blob/main/02-simple.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
